# Generated by Django 4.2.5 on 2023-11-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_pricehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricehistory',
            table='scrape_pricehistory',
        ),
    ]
