# Generated by Django 4.2.5 on 2023-11-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_alter_pricehistory_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='product',
            new_name='productItem',
        ),
        migrations.AddField(
            model_name='product',
            name='price_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_price_history', to='scrape.pricehistory'),
        ),
    ]
